name: Build
on: 
  push:
    paths:
      - 'pom.xml'
      - '**/src/**.java'
  pull_request:
    paths:
      - 'pom.xml'
      - '**/src/**.java'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
