name: Update Maven Wrapper
permissions:
  contents: write
on:
  push:
    branches:
      - master
    paths:
      - 'pom.xml'
jobs:
  update-maven-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build Maven Wrapper
        run: |
          mvn wrapper:wrapper
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add mvnw mvnw.cmd
          git commit -m "Update Maven Wrapper" || true
          git push origin HEAD:$GITHUB_REF || true
